"""Render research / spec / recipe / validation artifacts into a single
self-contained HTML file for human review.

Usage:
    python render.py research  <research.json>          <out.html>
    python render.py spec      <spec.md>                <out.html>
    python render.py recipe    <recipe.yaml>            <out.html>
    python render.py report    <generation_report.json> <out.html>

The `research` mode builds the visual, illustrated research report and is the
one the Dataset-Research skill uses. It delegates to build_research_report.py.

The HTML is fully inline (no external CSS/JS/fonts) so it can be deployed as a
Claude Code Artifact under a strict CSP. Tables scroll horizontally inside
their own container; the page never scrolls sideways.
"""
from __future__ import annotations

import html
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

# ---------------------------------------------------------------- styling ----

_CSS = """
:root{--bg:#0f1115;--panel:#171a21;--panel2:#1d212b;--ink:#e7ebf0;--muted:#9aa4b2;
--accent:#6ea8fe;--good:#4ade80;--warn:#fbbf24;--bad:#f87171;--line:#2a2f3a;}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;}
.wrap{max-width:1100px;margin:0 auto;padding:32px 20px 80px;}
h1{font-size:26px;margin:0 0 4px;letter-spacing:-.01em}
h2{font-size:19px;margin:34px 0 12px;padding-bottom:6px;border-bottom:1px solid var(--line)}
h3{font-size:15px;margin:20px 0 8px;color:var(--accent)}
.sub{color:var(--muted);margin:0 0 24px;font-size:14px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin:14px 0}
.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:14px 16px}
.card .k{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.04em}
.card .v{font-size:22px;font-weight:600;margin-top:4px}
.tablewrap{overflow-x:auto;border:1px solid var(--line);border-radius:10px;margin:10px 0}
table{border-collapse:collapse;width:100%;font-size:13.5px;min-width:480px}
th,td{padding:8px 12px;text-align:left;border-bottom:1px solid var(--line);white-space:nowrap}
th{background:var(--panel2);color:var(--muted);font-weight:600;position:sticky;top:0}
tr:last-child td{border-bottom:none}
td.num{text-align:right;font-variant-numeric:tabular-nums}
.pill{display:inline-block;padding:1px 9px;border-radius:999px;font-size:12px;font-weight:600}
.pill.good{background:rgba(74,222,128,.15);color:var(--good)}
.pill.warn{background:rgba(251,191,36,.15);color:var(--warn)}
.pill.bad{background:rgba(248,113,113,.15);color:var(--bad)}
.pill.info{background:rgba(110,168,254,.15);color:var(--accent)}
code,pre{font-family:"SF Mono",Menlo,Consolas,monospace}
pre{background:var(--panel);border:1px solid var(--line);border-radius:10px;
padding:14px 16px;overflow-x:auto;font-size:13px;line-height:1.5}
.bar{height:8px;border-radius:6px;background:var(--panel2);overflow:hidden;min-width:90px}
.bar>span{display:block;height:100%;background:var(--accent)}
.muted{color:var(--muted)}
.callout{background:var(--panel);border-left:3px solid var(--accent);
border-radius:6px;padding:12px 16px;margin:12px 0}
.callout.warn{border-left-color:var(--warn)}
ul.compact{margin:6px 0;padding-left:20px}
ul.compact li{margin:3px 0}
.spark{display:flex;align-items:flex-end;gap:2px;height:34px}
.spark>span{flex:1;background:var(--accent);opacity:.8;border-radius:1px 1px 0 0;min-width:3px}
.kvs{display:flex;flex-wrap:wrap;gap:6px 18px;margin:6px 0}
.kvs .k{color:var(--muted)}
a{color:var(--accent)}
.footer{margin-top:48px;color:var(--muted);font-size:12px;border-top:1px solid var(--line);padding-top:14px}
"""


def _page(title: str, body: str) -> str:
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title><style>{_CSS}</style></head>
<body><div class="wrap">{body}
<div class="footer">Generated by the DataGen plugin &middot; review and confirm before proceeding.</div>
</div></body></html>"""


def _esc(x: Any) -> str:
    return html.escape(str(x))


# ------------------------------------------------------ markdown (spec) ----

def _md_to_html(md: str) -> str:
    """A deliberately small Markdown subset renderer (headings, lists, tables,
    code fences, bold/italic/code spans, blockquotes). Good enough for the spec
    template we control; not a general-purpose parser."""
    lines = md.splitlines()
    out: List[str] = []
    i = 0
    n = len(lines)

    def inline(s: str) -> str:
        s = html.escape(s)
        import re
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", s)
        s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', s)
        return s

    while i < n:
        line = lines[i]
        if line.startswith("```"):
            buf = []
            i += 1
            while i < n and not lines[i].startswith("```"):
                buf.append(lines[i]); i += 1
            i += 1
            out.append("<pre>" + html.escape("\n".join(buf)) + "</pre>")
            continue
        if line.startswith("#"):
            level = len(line) - len(line.lstrip("#"))
            out.append(f"<h{min(level,3)}>{inline(line.lstrip('#').strip())}</h{min(level,3)}>")
            i += 1; continue
        if line.strip().startswith("|") and i + 1 < n and set(lines[i+1].strip()) <= set("|-: "):
            header = [c.strip() for c in line.strip().strip("|").split("|")]
            i += 2
            rows = []
            while i < n and lines[i].strip().startswith("|"):
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            th = "".join(f"<th>{inline(h)}</th>" for h in header)
            trs = "".join("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in r) + "</tr>" for r in rows)
            out.append(f'<div class="tablewrap"><table><thead><tr>{th}</tr></thead><tbody>{trs}</tbody></table></div>')
            continue
        if line.strip().startswith(("- ", "* ")):
            items = []
            while i < n and lines[i].strip().startswith(("- ", "* ")):
                items.append(lines[i].strip()[2:]); i += 1
            out.append('<ul class="compact">' + "".join(f"<li>{inline(it)}</li>" for it in items) + "</ul>")
            continue
        if line.strip().startswith(">"):
            out.append(f'<div class="callout">{inline(line.strip().lstrip(">").strip())}</div>')
            i += 1; continue
        if line.strip() == "":
            i += 1; continue
        out.append(f"<p>{inline(line)}</p>")
        i += 1
    return "\n".join(out)


def render_spec(md_path: str, out_path: str) -> None:
    md = Path(md_path).read_text(encoding="utf-8")
    title = "Dataset Research Spec"
    for l in md.splitlines():
        if l.startswith("# "):
            title = l[2:].strip(); break
    body = '<p class="sub">Domain research report. Review the grounded numbers and assumptions, then confirm.</p>'
    body += _md_to_html(md)
    Path(out_path).write_text(_page(title, body), encoding="utf-8")


# --------------------------------------------------------- recipe (yaml) ----

def _dist_summary(d: Dict[str, Any]) -> str:
    if not d:
        return '<span class="muted">n/a</span>'
    kind = d.get("kind", "?")
    parts = [f'<span class="pill info">{_esc(kind)}</span>']
    keys = [k for k in ("mean", "std", "min", "max", "lam", "alpha", "beta", "p", "shape", "scale") if k in d]
    if keys:
        kv = " ".join(f'<span class="k">{k}</span> {_esc(d[k])}' for k in keys)
        parts.append(f'<span class="kvs">{kv}</span>')
    if kind == "categorical":
        vals = d.get("values", {})
        tot = sum(vals.values()) or 1
        rows = "".join(
            f'<div class="kvs"><span class="k">{_esc(k)}</span>'
            f'<div class="bar" style="width:120px"><span style="width:{v/tot*100:.0f}%"></span></div>'
            f'<span>{v/tot*100:.0f}%</span></div>'
            for k, v in vals.items()
        )
        parts.append(rows)
    return " ".join(parts)


def render_recipe(yaml_path: str, out_path: str) -> None:
    import yaml
    recipe = yaml.safe_load(Path(yaml_path).read_text(encoding="utf-8"))
    meta = recipe.get("meta", {})
    title = f"Recipe: {meta.get('name','(unnamed)')}"

    body = [f"<h1>{_esc(meta.get('name','Recipe'))}</h1>"]
    body.append(f'<p class="sub">{_esc(meta.get("description",""))}</p>')

    # summary cards
    ents = recipe.get("entities", {})
    body.append('<div class="grid">')
    body.append(f'<div class="card"><div class="k">Datasets</div><div class="v">{len(recipe.get("datasets",[]))}</div></div>')
    body.append(f'<div class="card"><div class="k">Shared entities</div><div class="v">{len(ents)}</div></div>')
    body.append(f'<div class="card"><div class="k">Master seed</div><div class="v">{_esc(meta.get("seed","?"))}</div></div>')
    total_cols = sum(len(d.get("columns", {})) for d in recipe.get("datasets", []))
    body.append(f'<div class="card"><div class="k">Total columns</div><div class="v">{total_cols}</div></div>')
    body.append("</div>")

    if ents:
        body.append("<h2>Shared entities (referential integrity)</h2>")
        rows = "".join(
            f"<tr><td>{_esc(name)}</td><td><code>{_esc(e['key'])}</code></td>"
            f'<td class="num">{_esc(e["count"])}</td><td><code>{_esc(e.get("id_format","auto"))}</code></td></tr>'
            for name, e in ents.items()
        )
        body.append(f'<div class="tablewrap"><table><thead><tr><th>Entity</th><th>Key</th><th>Count</th><th>ID format</th></tr></thead><tbody>{rows}</tbody></table></div>')

    for ds in recipe.get("datasets", []):
        body.append(f"<h2>{_esc(ds['name'])}</h2>")
        meta_bits = []
        if ds.get("grain"): meta_bits.append(f'grain: {_esc(ds["grain"])}')
        if ds.get("primary_entity"): meta_bits.append(f'keyed on <code>{_esc(ds["primary_entity"])}</code>')
        if ds.get("rows") is not None: meta_bits.append(f'rows: <code>{_esc(ds["rows"])}</code>')
        if ds.get("inherit"):
            srcs = ", ".join(f"{i['from']}({','.join(i['columns'])})" for i in ds["inherit"])
            meta_bits.append(f'inherits: {_esc(srcs)}')
        if meta_bits:
            body.append(f'<p class="muted">{" &middot; ".join(meta_bits)}</p>')

        rows = []
        for cname, c in ds["columns"].items():
            badges = f'<span class="pill info">{_esc(c["type"])}</span>'
            if c.get("nullable"): badges += f' <span class="pill warn">{int(c["nullable"]*100)}% null</span>'
            if c.get("outliers"): badges += ' <span class="pill warn">outliers</span>'
            if c.get("correlate_with"):
                badges += f' <span class="pill good">&rho;={c["correlate_with"]["rho"]} w/ {_esc(c["correlate_with"]["column"])}</span>'
            if c.get("conditional"): badges += f' <span class="pill good">{len(c["conditional"])} conditional</span>'
            dist = _dist_summary(c.get("distribution", {})) if c.get("type") not in ("derived","faker","text") else (
                f'<code>{_esc(c.get("expr",""))}</code>' if c.get("type")=="derived" else
                f'faker:{_esc(c.get("faker",{}).get("provider","?"))}' if c.get("type")=="faker" else
                '<span class="pill info">LLM text</span>')
            rows.append(
                f"<tr><td><code>{_esc(cname)}</code></td><td>{badges}</td>"
                f'<td class="muted">{_esc(c.get("description",""))}</td><td>{dist}</td></tr>'
            )
        body.append(
            '<div class="tablewrap"><table><thead><tr><th>Column</th><th>Type</th><th>Description</th><th>Distribution / rule</th></tr></thead><tbody>'
            + "".join(rows) + "</tbody></table></div>"
        )

        cons = ds.get("constraints", [])
        if cons:
            body.append("<h3>Constraints</h3><ul class='compact'>")
            for c in cons:
                body.append(f'<li><code>{_esc(c["expr"])}</code> <span class="muted">({_esc(c.get("repair","resample"))})</span></li>')
            body.append("</ul>")

    Path(out_path).write_text(_page(title, "\n".join(body)), encoding="utf-8")


# ----------------------------------------------------- validation report ----

def _sparkbars(values: List[float]) -> str:
    if not values:
        return ""
    mx = max(values) or 1
    bars = "".join(f'<span style="height:{v/mx*100:.0f}%"></span>' for v in values)
    return f'<div class="spark">{bars}</div>'


def render_report(json_path: str, out_path: str) -> None:
    report = json.loads(Path(json_path).read_text(encoding="utf-8"))
    val = report.get("validation", {})
    title = f"Validation: {report.get('recipe','dataset')}"

    body = [f"<h1>Generated dataset, validation</h1>"]
    body.append(f'<p class="sub">Recipe <code>{_esc(report.get("recipe",""))}</code>. '
                'Every dataset below was generated deterministically and checked against the recipe.</p>')

    # top-line cards
    ds_reports = val.get("datasets", {})
    ri = val.get("referential_integrity", [])
    ri_ok = all(r["ok"] for r in ri) if ri else True
    warns = val.get("warnings", [])
    body.append('<div class="grid">')
    body.append(f'<div class="card"><div class="k">Datasets</div><div class="v">{len(ds_reports)}</div></div>')
    total_rows = sum(d.get("rows", 0) for d in ds_reports.values())
    body.append(f'<div class="card"><div class="k">Total rows</div><div class="v">{total_rows:,}</div></div>')
    ri_pill = '<span class="pill good">OK</span>' if ri_ok else '<span class="pill bad">orphans</span>'
    body.append(f'<div class="card"><div class="k">Referential integrity</div><div class="v">{ri_pill}</div></div>')
    w_pill = f'<span class="pill good">0</span>' if not warns else f'<span class="pill warn">{len(warns)}</span>'
    body.append(f'<div class="card"><div class="k">Warnings</div><div class="v">{w_pill}</div></div>')
    body.append("</div>")

    if warns:
        body.append('<div class="callout warn"><strong>Warnings</strong><ul class="compact">'
                    + "".join(f"<li>{_esc(w)}</li>" for w in warns) + "</ul></div>")

    if ri:
        body.append("<h2>Referential integrity</h2>")
        rows = "".join(
            f"<tr><td><code>{_esc(r['dataset'])}.{_esc(r['column'])}</code></td>"
            f"<td>&rarr; {_esc(r['references'])}</td>"
            f'<td class="num">{r["orphans"]}</td>'
            f'<td>{"<span class=\'pill good\'>ok</span>" if r["ok"] else "<span class=\'pill bad\'>fail</span>"}</td></tr>'
            for r in ri
        )
        body.append(f'<div class="tablewrap"><table><thead><tr><th>Foreign key</th><th>References</th><th>Orphans</th><th>Status</th></tr></thead><tbody>{rows}</tbody></table></div>')

    for name, d in ds_reports.items():
        body.append(f"<h2>{_esc(name)} <span class='muted'>&middot; {d.get('rows',0):,} rows</span></h2>")
        rows = []
        for col, s in d.get("columns", {}).items():
            if "mean" in s:
                stats = (f'<span class="kvs"><span class="k">mean</span>{s["mean"]:.2f}'
                         f'<span class="k">std</span>{s.get("std",0):.2f}'
                         f'<span class="k">min</span>{s["min"]:.1f}'
                         f'<span class="k">med</span>{s["median"]:.1f}'
                         f'<span class="k">max</span>{s["max"]:.1f}</span>')
            elif "top_values" in s:
                tv = s["top_values"]
                stats = _sparkbars(list(tv.values())) + " " + ", ".join(
                    f'{_esc(k)} <span class="muted">{v}</span>' for k, v in list(tv.items())[:5])
                stats += f' <span class="muted">({s.get("n_unique","?")} unique)</span>'
            else:
                stats = '<span class="muted">n/a</span>'
            fid = ""
            f = s.get("fidelity")
            if f and "mean_target" in f:
                fid = f' <span class="pill info">target &mu;={f["mean_target"]} &rarr; {f["mean_actual"]}</span>'
            nullpill = f' <span class="pill warn">{s["n_null"]} null</span>' if s.get("n_null") else ""
            rows.append(f"<tr><td><code>{_esc(col)}</code></td><td class='muted'>{_esc(s['dtype'])}{nullpill}</td><td>{stats}{fid}</td></tr>")
        body.append('<div class="tablewrap"><table><thead><tr><th>Column</th><th>Type</th><th>Summary</th></tr></thead><tbody>'
                    + "".join(rows) + "</tbody></table></div>")
        drift = d.get("categorical_drift")
        if drift:
            body.append("<h3>Categorical drift (actual minus target share)</h3>")
            for col, dd in drift.items():
                chips = " ".join(
                    f'<span class="pill {"good" if abs(v)<0.03 else "warn"}">{_esc(k)} {v:+.2f}</span>'
                    for k, v in dd.items())
                body.append(f"<p><code>{_esc(col)}</code>: {chips}</p>")

    Path(out_path).write_text(_page(title, "\n".join(body)), encoding="utf-8")


def render_research(json_path: str, out_path: str) -> None:
    """Visual research report from a research.json. Delegates to the dedicated
    builder so the chart/illustration logic lives in one place."""
    import build_research_report as brr
    data = json.loads(Path(json_path).read_text(encoding="utf-8"))
    Path(out_path).write_text(brr.build(data), encoding="utf-8")


def main(argv: List[str]) -> int:
    if len(argv) < 3:
        print(__doc__)
        return 2
    mode, src, out = argv[0], argv[1], argv[2]
    if mode == "research":
        render_research(src, out)
    elif mode == "spec":
        render_spec(src, out)
    elif mode == "recipe":
        render_recipe(src, out)
    elif mode == "report":
        render_report(src, out)
    else:
        print(f"unknown mode: {mode}")
        return 2
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
